name: build
on: [push]
jobs:
  test:
    env:
      CI: true
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - id: nvm
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
    - uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - run: npm ci
    - run: npm run lint
      if: matrix.os != 'windows-latest'
    - run: xvfb-run -a npm test
      if: matrix.os == 'ubuntu-latest'
    - run: npm test
      if: matrix.os != 'ubuntu-latest'
